### ISSUE TITLE
backend-kaizen

### ISSUE THREAD

**Issue by shirakurak** [shirakurak/something#11]
バックエンド部分で一応動くことは確認したが、改善点は多い。
以下、記録しておく。
- バックエンド手順書の修正
  - [x] `4. MySQL`について、DDL/DMLの用意
    - [x] それに伴い、バックエンドの手順書を修正
    - [x] ddlやsqlファイルからmysqlファイルを実行できるか確認 
      - 移動#17へ
  - [x] 全体的な修正見直し
    - #16 追加
- 実装
  - [x] `ResultMap`の指定が、Entity側で指定できないか確認 (soma)
    - `https://github.com/shirakurak/something/blob/11-backend-kaizen/dogs/backend/src/main/java/com/example/demo/entity/Dog.java`になんらかの記載をすることで、`https://github.com/shirakurak/something/blob/11-backend-kaizen/dogs/backend/src/main/resources/com/example/demo/repository/DogMapper.xml`のid=`dogsResultMap`部分の記載を消去することは可能か？
  - [x] `where`句について、`#{userName}`が`null`の場合あるし、`<where>`使う？

**Comment by shirakurak** [comment]
画像データの取得方法について、別途調査必要

**Comment by shirakurak** [comment]
`UserController`に関する修正
- [x] URLを適切なものに修正
  - @RequestMapping("/login/userId/{userId}/password/{password}") の password部分をなくして適切なURLにする
- [x] ワンちゃん一覧を取得する部分は、`DogsController`にする

**Comment by shirakurak** [comment]
次のブランチを作成：`11-backend-kaizen`

@nakamura0067 
issue 11でやれそうなことがありましたら、対応して頂けるとありがたしです。

**Comment by nakamura0067** [comment]
> ResultMapの指定が、Entity側で指定できないか確認 (soma)

Entity側での指定は無理そう。Mapper側で以下の3パターンで実現が可能。
1. `<select id="xxx" resultType="Entityの完全修飾クラス名"`でマッピング可能
    - Entityのパラメータとテーブルのカラム名が完全一致している必要あり 
2. select文にカラム名を指定し、`as "Entityのパラメータ名"`をカラム名の後ろにつけてマッピング
3. resultMapを定義する（今はこれで実装している）

- 参考：https://mybatis.org/mybatis-3/ja/sqlmap-xml.html#Result_Maps

**Comment by nakamura0067** [comment]
> where句について、#{userName}がnullの場合あるし、<where>使う？

`<where>`に修正
IFの定義上、userId,userPasswordは必須としているため、nullの考慮は行わないものとする

**Comment by nakamura0067** [comment]
Spring JPA使ったらMapperそのものがなくてもよくなった

- https://kohei.life/spring-data-jpa-use/
- https://qiita.com/shindo_ryo/items/af7d12be264c2cc4b252
