### ISSUE TITLE
テーブル定義検討

### ISSUE THREAD

**Issue by shirakurak** [shirakurak/something#16]
現状は以下があるのみ：
 - `dogs/docs/dogs.ddl`
 - `dogs/docs/test_data.sql`

その他の格納する必要のあるデータを検討する。制約や正規化等についても考える。

**Comment by nakamura0067** [comment]
![image](https://user-images.githubusercontent.com/61833424/142972674-d74b1feb-e471-4665-935f-dc17d082b35e.png)
カラム名の`user_`や`dog_`のプレフィックス的なものはテーブル名と重複しているし不要では？

**Comment by nakamura0067** [comment]
https://qiita.com/sato-shin/items/0ec486d9c1bf98d9bf4c
`
id`のstring型を希望。桁数は要相談。
`00000001`みたいなゼロ始まり許容で桁数揃えたい。

**Comment by shirakurak** [comment]
上記のddlの対応とそれに伴う実装の修正については、#17で対応する。

**Comment by nakamura0067** [comment]
カラム名の変更、dogsにimage_pathのカラム追加を確認
