### ISSUE TITLE
ワンちゃん画像の格納と取得

### ISSUE THREAD

**Issue by shirakurak** [shirakurak/something#17]
格納
- [x] `/backend/src/main/resources`配下に画像格納用ディレクトリを作成する
- [x] ワンちゃんの画像を格納する

取得
- [x] DDL修正
- [x] 上記で格納した画像を取得する処理を実装
- [x] 実際に画面に表示されるか確認

おそらく`frontend`のほうと連携する必要もあり。

**Comment by nakamura0067** [comment]
画像の送信処理まで作成したことを確認。
画像データの型などについて、フロントエンド側で調整が必要。
コンフリクト起きるので、マージよろしく

**Comment by nakamura0067** [comment]
Usersテーブルについて、
id = "shirakurak"
name = "白倉K"
password = "P@ssw0rd"
という仕様に決定

**Comment by nakamura0067** [comment]
以下のタスクを#11から移動

- [x] ddlやsqlファイルからmysqlファイルを実行できるか確認

**Comment by shirakurak** [comment]
test

**Comment by shirakurak** [comment]
test2

**Comment by shirakurak** [comment]
test3

**Comment by shirakurak** [comment]
現状のdevelopを17-image-codingにマージ(conflictの解消)を行った。

**Comment by shirakurak** [comment]
画像の取得と実際の表示まで確認。pushした。

**Comment by shirakurak** [comment]
> 以下のタスクを#11から移動
> 
>     * [x]  ddlやsqlファイルからmysqlファイルを実行できるか確認

同時に実行できるバッチファイルを作成

**Comment by shirakurak** [comment]
17-image-codingをdevelopにマージしたため、クローズする。
