### ISSUE TITLE
バイナリ対応

### ISSUE THREAD

**Issue by nakamura0067** [shirakurak/something#32]
- フロントエンドサーバ → nakamura
  - 受け取ったバイナリデータを画像として表示
- バックエンドサーバ → shirakura
  - 静的リソースをバイナリデータとしてフロントへ送信
  - CORSも対応

**Comment by shirakurak** [comment]
画像ファイルをbyte[]型にして、Base64にエンコードしてレスポンスに入れるようにしました。
認識会っていますでしょうか。
Reactのほうでencodingすれば表示されるはず？

※CORSアノテーションはまだ付与してません。

**Comment by shirakurak** [comment]
できた
