### ISSUE TITLE
GitHubからPlantumlの描画が見えない

### ISSUE THREAD

**Issue by nakamura0067** [shirakurak/something#5]

**Comment by nakamura0067** [comment]
chromeで以下の拡張機能を追加することで解決

[pegmatite](https://chrome.google.com/webstore/detail/pegmatite/jegkfbnfbfnohncpcfcimepibmhlkldo)

**Comment by shirakurak** [comment]
firefoxの場合、以下：
[PlantUML Extension](https://addons.mozilla.org/ja/firefox/addon/plantuml-extension/)
